#!/bin/bash

sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/sites-available/default

sed -i 's/user\s\+www-data;/user nginx;/g' /etc/nginx/nginx.conf

systemctl restart nginx

ps aux | grep ngin[x]

nc -z 0 8080; echo $?