#!/usr/bin/env bash

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
systemctl restart nginx

ps auxff | grep ngin[x]
nc -z 0 8080
